### ISSUE TITLE
VOMS extension missing

### ISSUE THREAD

**Issue by romainreuillon** [Misenko/jOCCI-api#1]
Hi,

I tried to connect to the EGI federated cloud using the version 0.2.0 and I got this error:

```
[error] {"error": {"message": "(5, VOMS extension missing)", "code": 400, "title": "Bad Request"}}
cz.cesnet.cloud.occi.api.exception.CommunicationException: HTTP/1.1 400 Bad Request
{"error": {"message": "(5, VOMS extension missing)", "code": 400, "title": "Bad Request"}}
    at cz.cesnet.cloud.occi.api.http.HTTPHelper.runRequest(HTTPHelper.java:122)
    at cz.cesnet.cloud.occi.api.http.HTTPHelper.runRequest(HTTPHelper.java:132)
    at cz.cesnet.cloud.occi.api.http.auth.KeystoneAuthentication.authenticateAgainstKeystone(KeystoneAuthentication.java:125)
    at cz.cesnet.cloud.occi.api.http.auth.KeystoneAuthentication.authenticate(KeystoneAuthentication.java:111)
    at cz.cesnet.cloud.occi.api.http.auth.HTTPAuthentication.authenticate(HTTPAuthentication.java:191)
    at cz.cesnet.cloud.occi.api.http.auth.CertificateAuthentication.authenticate(CertificateAuthentication.java:228)
    at cz.cesnet.cloud.occi.api.http.HTTPClient.connect(HTTPClient.java:164)
    at cz.cesnet.cloud.occi.api.http.HTTPClient.<init>(HTTPClient.java:107)
    at cz.cesnet.cloud.occi.api.http.HTTPClient.<init>(HTTPClient.java:119)
```

Do you have any idea why?

cheers,
Romain

**Comment by amarthadan** [comment]
Hi.

This error probably mean that you didn't use valid credentials. To authenticate against Keystone you have to use VOMS proxy. You have to generate VOMS proxy via `voms-proxy-init` and then pass the path to the file (usually `/tmp/x509up_u1000`) to `VOMSAuthentication` instance.
